Vagrant.configure("2") do |config|
    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "bento/ubuntu-20.04"
      ubuntu.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
      ubuntu.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.gui = true
      end
  
      ubuntu.vm.provision "shell", inline: <<-SHELL
  
        # Updates, upgrades, and installs git
        sudo apt update
        sudo apt upgrade -y
        sudo apt install git
  
        # Clones repo with all scripts
        git clone https://github.com/Co1orguard/DCIG_Vagrant.git
        cd DCIG_Vagrant/Firewalls

        # Runs installs
        /Linux/installs.sh
        
        # Reboots system for changes to take effect
        sudo reboot
  
      SHELL
    end
  
    config.vm.define "windows" do |windows|
      windows.vm.box = "StefanScherer/windows_10"
      windows.vm.synced_folder ".", "/vagrant"
  
      windows.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.gui = true
      end
    end
  end